"""GoreeCloud Search core package."""

from .brave_provider import (
    BRAVE_MAX_QUERY_CHARS,
    BRAVE_MAX_QUERY_WORDS,
    BRAVE_MAX_RESULTS,
    BRAVE_WEB_SEARCH_URL,
    BraveSearchProviderError,
    BraveSearchTransport,
    BraveWebSearchProvider,
    BraveWebSearchRequest,
    UrllibBraveSearchTransport,
)
from .content_policy import (
    ContentPolicyAction,
    ContentPolicyDecision,
    ContentPolicyEngine,
    ContentPolicyError,
    ContentPolicyHook,
    ContentPolicyOutcome,
    ContentPolicyReport,
    DomainPolicyHook,
    SafeSearchMode,
)
from .execution import (
    ExecutionPolicy,
    ExecutionReport,
    ProviderAttempt,
    ProviderExecutionError,
    ProviderExecutionStatus,
    SearchAvailability,
    SearchExecutor,
)
from .http_api import (
    DEFAULT_LOCAL_SEARCH_PORT,
    LOCAL_SEARCH_HOST,
    MAX_HTTP_QUERY_CHARS,
    MAX_HTTP_REQUEST_TARGET_CHARS,
    MAX_HTTP_RESULT_LIMIT,
    LocalSearchAPIError,
    LocalSearchHTTPServer,
    create_local_server,
)
from .index_contract import (
    INDEX_CONTRACT_VERSION,
    IndexCapabilities,
    IndexContractError,
    IndexDocumentCandidate,
    IndexSearchRequest,
    IndexSearchResponse,
)
from .index_provider import (
    GoreeCloudIndexProvider,
    IndexTransport,
)
from .lens_contract import (
    LENS_FORMAT_VERSION,
    MAX_LENS_DOCUMENT_BYTES,
    MAX_LENS_RULES,
    LensFormatError,
    export_lens,
    import_lens,
    lens_to_document,
)
from .lenses import (
    Lens,
    LensApplicationReport,
    LensError,
    LensExclusion,
    LensRegistry,
    LensRule,
    LensRuleAction,
    LensRuleTarget,
    apply_lens,
)
from .models import (
    ParsedQuery,
    ProviderDescriptor,
    ProviderOrigin,
    QueryDisclosureBudget,
    QueryFilters,
    SearchCategory,
    SourceMode,
    SourcePlan,
    SourcePlanStep,
)
from .normalization import (
    NormalizedResult,
    ResultNormalizationError,
    ResultProvenance,
    canonicalize_url,
    normalize_and_deduplicate,
)
from .planner import (
    SourcePlanningError,
    plan_sources,
)
from .providers import (
    ProviderSearchBatch,
    ResultCandidate,
    SearchProvider,
)
from .query_parser import (
    QueryParseError,
    parse_query,
)
from .ranking import (
    RankedResult,
    RankingSignal,
    rank_results,
)
from .service import SearchCore, SearchResponse
from .snippets import (
    DEFAULT_SNIPPET_MAX_CHARS,
    MAX_SNIPPET_SOURCE_CHARS,
    GeneratedSnippet,
    SnippetGenerationError,
    generate_snippet,
)
from .version import __version__

__all__ = [
    "__version__",
    "INDEX_CONTRACT_VERSION",
    "LOCAL_SEARCH_HOST",
    "DEFAULT_LOCAL_SEARCH_PORT",
    "MAX_HTTP_QUERY_CHARS",
    "MAX_HTTP_REQUEST_TARGET_CHARS",
    "MAX_HTTP_RESULT_LIMIT",
    "LocalSearchAPIError",
    "LocalSearchHTTPServer",
    "create_local_server",
    "BRAVE_WEB_SEARCH_URL",
    "BRAVE_MAX_RESULTS",
    "BRAVE_MAX_QUERY_CHARS",
    "BRAVE_MAX_QUERY_WORDS",
    "BraveSearchProviderError",
    "BraveSearchTransport",
    "BraveWebSearchProvider",
    "BraveWebSearchRequest",
    "UrllibBraveSearchTransport",
    "ContentPolicyAction",
    "ContentPolicyDecision",
    "ContentPolicyEngine",
    "ContentPolicyError",
    "ContentPolicyHook",
    "ContentPolicyOutcome",
    "ContentPolicyReport",
    "DomainPolicyHook",
    "SafeSearchMode",
    "LENS_FORMAT_VERSION",
    "MAX_LENS_DOCUMENT_BYTES",
    "MAX_LENS_RULES",
    "LensFormatError",
    "export_lens",
    "import_lens",
    "lens_to_document",
    "Lens",
    "LensRule",
    "LensRuleAction",
    "LensRuleTarget",
    "LensRegistry",
    "LensError",
    "LensExclusion",
    "LensApplicationReport",
    "apply_lens",
    "ParsedQuery",
    "ProviderDescriptor",
    "ProviderOrigin",
    "QueryDisclosureBudget",
    "QueryFilters",
    "SearchCategory",
    "SourceMode",
    "SourcePlan",
    "SourcePlanStep",
    "QueryParseError",
    "SourcePlanningError",
    "IndexContractError",
    "ResultNormalizationError",
    "ProviderExecutionError",
    "IndexCapabilities",
    "IndexDocumentCandidate",
    "IndexSearchRequest",
    "IndexSearchResponse",
    "GoreeCloudIndexProvider",
    "IndexTransport",
    "ResultCandidate",
    "ProviderSearchBatch",
    "SearchProvider",
    "ResultProvenance",
    "NormalizedResult",
    "canonicalize_url",
    "normalize_and_deduplicate",
    "RankingSignal",
    "RankedResult",
    "rank_results",
    "ExecutionPolicy",
    "ProviderExecutionStatus",
    "ProviderAttempt",
    "ExecutionReport",
    "SearchAvailability",
    "SearchExecutor",
    "SearchResponse",
    "DEFAULT_SNIPPET_MAX_CHARS",
    "MAX_SNIPPET_SOURCE_CHARS",
    "GeneratedSnippet",
    "SnippetGenerationError",
    "generate_snippet",
    "parse_query",
    "plan_sources",
    "SearchCore",
]
