# yamllint disable rule:line-length
name: Platform Contract

"on":
  pull_request:
    paths:
      - goreecloud.platform.yaml
      - .github/workflows/platform-contract.yml
  push:
    branches:
      - master
    paths:
      - goreecloud.platform.yaml
      - .github/workflows/platform-contract.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: GoreeCloud/GoreeCloud/.github/workflows/reusable-platform-manifest.yml@3204afc4f603f3b29a456f01cbb28755d7f7bd00
    with:
      manifest-path: goreecloud.platform.yaml
